stages:
  - prepare
  - build
  - release

variables:
  DOCKER_DRIVER: overlay2

default:
  image: python:3.11
  before_script:
    - python --version
    - pip install --upgrade pip

generate_example_recipes:
  stage: prepare
  script:
    - python src/firmware/generate_example_recieps.py
  artifacts:
    paths:
      - src/firmware/src/static_modules/example_recipes.py
    expire_in: 1 week

build_firmware:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk add --no-cache bash git
  script:
    - bash src/firmware/build_firmware_docker.sh
  dependencies:
    - generate_example_recipes
  artifacts:
    paths:
      - src/firmware/build
    expire_in: 1 week

tag_firmware:
  stage: release
  image: alpine/git:latest
  needs:
    - job: build_firmware
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  before_script:
    - git config --global user.name "gitlab-ci"
    - git config --global user.email "gitlab-ci@example.com"
    - git fetch --tags
  script:
    - |
      TAG_PREFIX="firmware-"
      SHORT_SHA="${CI_COMMIT_SHA:0:7}"
      TAG_NAME="${TAG_PREFIX}${SHORT_SHA}"
      if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
        echo "Tag $TAG_NAME already exists. Skipping."
      else
        git tag "$TAG_NAME" "$CI_COMMIT_SHA"
        git push "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" "$TAG_NAME"
        echo "Created tag $TAG_NAME"
      fi
tag_firmware:
  stage: build
  image: alpine/git:latest
  needs:
    - job: build_firmware
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  before_script:
    - git config --global user.name "gitlab-ci"
    - git config --global user.email "gitlab-ci@example.com"
    - git fetch --tags
  script:
    - |
      TAG_PREFIX="firmware-"
      SHORT_SHA="${CI_COMMIT_SHA:0:7}"
      TAG_NAME="${TAG_PREFIX}${SHORT_SHA}"
      if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
        echo "Tag $TAG_NAME already exists. Skipping."
      else
        git tag "$TAG_NAME" "$CI_COMMIT_SHA"
        git push "https://${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" "$TAG_NAME"
        echo "Created tag $TAG_NAME"
      fi
