apiVersion: v1
kind: Pod
metadata:
  name: mixmeasurebuddy-suite
  labels:
    app: mixmeasurebuddy-suite
spec:
  containers:
    - name: backend
      image: mixmeasurebuddy-suite-backend:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: PORT
          value: '4000'
        - name: RECIPE_STORAGE
          value: /data/systems
        - name: RECIPE_DB_PATH
          value: /data/mixmeasurebuddy.sqlite
      ports:
        - containerPort: 4000
      readinessProbe:
        httpGet:
          path: /
          port: 4000
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 4000
        initialDelaySeconds: 15
        periodSeconds: 20
      volumeMounts:
        - name: mixmeasurebuddy-suite-backend-data
          mountPath: /data
    - name: frontend
      image: mixmeasurebuddy-suite-frontend:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: NEXT_PUBLIC_BACKEND_URL
          value: http://localhost:4000
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
    - name: proxy
      image: mixmeasurebuddy-suite-proxy:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 15
  volumes:
    - name: mixmeasurebuddy-suite-backend-data
      emptyDir: {}
