services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - RECIPE_STORAGE=/data/systems
      - RECIPE_DB_PATH=/data/assignments.json
    volumes:
      - backend-data:/data
    restart: unless-stopped

  web:
    build:
      context: ./frontend
      dockerfile:  Dockerfile
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:4000
    ports:
      - '8080:80'
    restart: unless-stopped

volumes:
  backend-data:
