# Auto-generated by generate_example_recieps.py; do not edit manually.
import recipe

def RECIPES_COLLECTION_MOJITO() -> recipe.recipe:
    recipe_obj: recipe.recipe = recipe.recipe('Mojito', 'A classic Cuban cocktail combining fresh mint, lime juice, rum, sugar, and soda water for a perfectly refreshing drink.', '1.0.0', ['everything'])
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Mint Leaves',
        _current_step_text='Add fresh mint leaves and sugar to the glass',
        _target_value=8,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='White Sugar',
        _current_step_text='',
        _target_value=10,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Muddle mint and sugar together',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Fresh Lime Juice',
        _current_step_text='',
        _target_value=30,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='White Rum',
        _current_step_text='',
        _target_value=50,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Ice',
        _current_step_text='Add ice cubes',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Soda Water',
        _current_step_text='',
        _target_value=60,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Mint Sprig',
        _current_step_text='Stir gently and garnish with mint sprig and lime slice',
        _target_value=1,
    ))
    recipe_obj.valid = True
    return recipe_obj

def RECIPES_COLLECTION_MARGARITA() -> recipe.recipe:
    recipe_obj: recipe.recipe = recipe.recipe('Margarita', 'A classic cocktail made with tequila, triple sec, and lime juice, served in a salt-rimmed glass for the perfect balance of tart and sweet.', '1.0.0', ['everything'])
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Salt',
        _current_step_text='Rim the glass with salt',
        _target_value=2,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Tequila',
        _current_step_text='',
        _target_value=50,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Triple Sec',
        _current_step_text='',
        _target_value=25,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Fresh Lime Juice',
        _current_step_text='',
        _target_value=25,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Ice',
        _current_step_text='Add ice cubes to shaker',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Shake well until chilled',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Strain into the prepared glass with ice',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Lime Wheel',
        _current_step_text='Garnish with a lime wheel',
        _target_value=1,
    ))
    recipe_obj.valid = True
    return recipe_obj

def RECIPES_COLLECTION_RAMOS_GIN_FIZZ() -> recipe.recipe:
    recipe_obj: recipe.recipe = recipe.recipe('Ramos Gin Fizz', 'Rich, frothy gin fizz with cream, citrus, and orange blossom.', '1.0.0', ['everything'])
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Ice',
        _current_step_text='Add ice to the shaker',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Gin',
        _current_step_text='',
        _target_value=45,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Lemon Juice',
        _current_step_text='',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Lime Juice',
        _current_step_text='',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Simple Syrup',
        _current_step_text='',
        _target_value=20,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Heavy Cream',
        _current_step_text='',
        _target_value=30,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Egg White',
        _current_step_text='Add egg white',
        _target_value=1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Orange Flower Water',
        _current_step_text='Add orange flower water',
        _target_value=2,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Shake until well chilled',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Strain into a prepared glass',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Soda Water',
        _current_step_text='Top slowly with soda water',
        _target_value=90,
    ))
    recipe_obj.valid = True
    return recipe_obj

def RECIPES_COLLECTION_OLD_FASHIONED() -> recipe.recipe:
    recipe_obj: recipe.recipe = recipe.recipe('Old Fashioned', 'A timeless cocktail made with bourbon, bitters, and sugar, stirred over ice and finished with an orange peel and cherry garnish.', '1.0.0', ['everything'])
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Sugar Cube',
        _current_step_text='Add sugar cube and bitters to glass',
        _target_value=1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Angostura Bitters',
        _current_step_text='',
        _target_value=2,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Muddle until sugar is dissolved',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Bourbon Whiskey',
        _current_step_text='',
        _target_value=60,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Ice',
        _current_step_text='Add large ice cube',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Stir gently to chill and mix',
        _target_value=10,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Orange Peel',
        _current_step_text='Garnish with orange peel and cherry',
        _target_value=1,
    ))
    recipe_obj.valid = True
    return recipe_obj

def RECIPES_COLLECTION_GIN_BASIL_SMASH() -> recipe.recipe:
    recipe_obj: recipe.recipe = recipe.recipe('Gin Basil Smash', 'Vibrant gin sour infused with muddled basil and lemon.', '1.0.0', ['everything'])
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Basil Leaves',
        _current_step_text='Muddle basil leaves with lemon juice in the shaker',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Ice',
        _current_step_text='Add ice to the shaker',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Gin',
        _current_step_text='',
        _target_value=60,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Lemon Juice',
        _current_step_text='',
        _target_value=25,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Simple Syrup',
        _current_step_text='',
        _target_value=20,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Basil Leaves',
        _current_step_text='',
        _target_value=8,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Shake until well chilled',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Strain into a prepared glass',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Basil Leaf',
        _current_step_text='Garnish with a basil leaf',
        _target_value=1,
    ))
    recipe_obj.valid = True
    return recipe_obj

def RECIPES_COLLECTION_SINGAPORE_SLING() -> recipe.recipe:
    recipe_obj: recipe.recipe = recipe.recipe('Singapore Sling', 'Layered gin sling with cherry, citrus, and sparkling length.', '1.0.0', ['everything'])
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Ice',
        _current_step_text='Add ice to the shaker',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Gin',
        _current_step_text='',
        _target_value=30,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Cherry Heering',
        _current_step_text='',
        _target_value=20,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Cointreau',
        _current_step_text='',
        _target_value=10,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Bénédictine',
        _current_step_text='',
        _target_value=10,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Pineapple Juice',
        _current_step_text='',
        _target_value=90,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Lime Juice',
        _current_step_text='',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Grenadine',
        _current_step_text='',
        _target_value=10,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Shake until well chilled',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Strain into a prepared glass',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Soda Water',
        _current_step_text='Top with soda water',
        _target_value=60,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Pineapple Wedge',
        _current_step_text='Garnish with pineapple and cherry',
        _target_value=1,
    ))
    recipe_obj.valid = True
    return recipe_obj

def RECIPES_COLLECTION_ROSEMARY_GREYHOUND() -> recipe.recipe:
    recipe_obj: recipe.recipe = recipe.recipe('Rosemary Greyhound', 'Botanical vodka highball with grapefruit and rosemary.', '1.0.0', ['everything'])
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Rosemary Sprig',
        _current_step_text='Lightly muddle rosemary in the glass',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Ice',
        _current_step_text='Fill the serving glass with ice',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Vodka',
        _current_step_text='',
        _target_value=50,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Grapefruit Juice',
        _current_step_text='',
        _target_value=120,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Simple Syrup',
        _current_step_text='',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Stir gently to combine',
        _target_value=10,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Rosemary Sprig',
        _current_step_text='Garnish with a rosemary sprig',
        _target_value=1,
    ))
    recipe_obj.valid = True
    return recipe_obj

def RECIPES_COLLECTION_HURRICANE() -> recipe.recipe:
    recipe_obj: recipe.recipe = recipe.recipe('Hurricane', 'Passion fruit-forward rum punch from New Orleans.', '1.0.0', ['everything'])
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Ice',
        _current_step_text='Add ice to the shaker',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Light Rum',
        _current_step_text='',
        _target_value=45,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Dark Rum',
        _current_step_text='',
        _target_value=45,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Passion Fruit Syrup',
        _current_step_text='',
        _target_value=30,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Orange Juice',
        _current_step_text='',
        _target_value=45,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Lime Juice',
        _current_step_text='',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Grenadine',
        _current_step_text='',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Shake until well chilled',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Strain into a prepared glass',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Orange Slice',
        _current_step_text='Garnish with an orange slice and cherry',
        _target_value=1,
    ))
    recipe_obj.valid = True
    return recipe_obj

def RECIPES_COLLECTION_BLACK_RUSSIAN() -> recipe.recipe:
    recipe_obj: recipe.recipe = recipe.recipe('Black Russian', 'Simple blend of vodka and coffee liqueur served over ice.', '1.0.0', ['everything'])
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Ice',
        _current_step_text='Fill the serving glass with ice',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Vodka',
        _current_step_text='',
        _target_value=50,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Coffee Liqueur',
        _current_step_text='',
        _target_value=25,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Stir gently to combine',
        _target_value=10,
    ))
    recipe_obj.valid = True
    return recipe_obj

def RECIPES_COLLECTION_WHISKEY_SOUR() -> recipe.recipe:
    recipe_obj: recipe.recipe = recipe.recipe('Whiskey Sour', 'A smooth and tangy cocktail made with bourbon, lemon juice, and simple syrup, served over ice and garnished with citrus and cherry.', '1.0.0', ['everything'])
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Bourbon Whiskey',
        _current_step_text='',
        _target_value=60,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Fresh Lemon Juice',
        _current_step_text='',
        _target_value=30,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.SCALE,
        _ingredient_name='Simple Syrup',
        _current_step_text='',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Ice',
        _current_step_text='Add ice cubes to shaker',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Shake well until chilled',
        _target_value=15,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.WAIT,
        _ingredient_name='',
        _current_step_text='Strain into an old-fashioned glass with fresh ice',
        _target_value=-1,
    ))
    recipe_obj.add_step(recipe.recipe_step(
        _action=recipe.USER_INTERACTION_MODE.CONFIRM,
        _ingredient_name='Orange Slice',
        _current_step_text='Garnish with an orange slice and a maraschino cherry',
        _target_value=1,
    ))
    recipe_obj.valid = True
    return recipe_obj

def GET_EXAMPLE_RECIPES_COLLECTION() -> list[recipe.recipe]:
    return [
        RECIPES_COLLECTION_MOJITO(),
        RECIPES_COLLECTION_MARGARITA(),
        RECIPES_COLLECTION_RAMOS_GIN_FIZZ(),
        RECIPES_COLLECTION_OLD_FASHIONED(),
        RECIPES_COLLECTION_GIN_BASIL_SMASH(),
        RECIPES_COLLECTION_SINGAPORE_SLING(),
        RECIPES_COLLECTION_ROSEMARY_GREYHOUND(),
        RECIPES_COLLECTION_HURRICANE(),
        RECIPES_COLLECTION_BLACK_RUSSIAN(),
        RECIPES_COLLECTION_WHISKEY_SOUR()
    ]
