name: Build Firmware

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate example recipes module
        run: python src/firmware/generate_example_recieps.py

      - name: Build firmware via Docker helper
        run: bash src/firmware/build_firmware_docker.sh

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-build
          path: src/firmware/build
          if-no-files-found: warn

      - name: Create firmware tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TAG_PREFIX: firmware-
        run: |
          set -euo pipefail
          TAG_NAME="${TAG_PREFIX}${GITHUB_SHA::7}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --tags
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Skipping creation."
          else
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"
            echo "Created and pushed tag $TAG_NAME"
          fi
