name: Build Firmware

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate example recipes module
        run: python src/firmware/generate_example_recieps.py

      - name: Build firmware via Docker helper
        run: bash src/firmware/build_firmware_docker.sh

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-build
          path: src/firmware/build
          if-no-files-found: warn
