services:

  mmb_web:
    build:
      context: apache2
    volumes:
      - ${PWD}/apache2/html:/var/www/
      - ${PWD}/apache2/sites-enabled:/etc/apache2/sites-enabled/
    environment: 
      - API_SERVER_ADDR=mmb_api:5500  
      - FRONTEND_SERVER_ADDR=mmb_frontend:3000  

    ports:
      - 10443:80 #HOST:CONTAINER
    depends_on:
      - mmb_api
      - mmb_frontend
    links:
      - "mmb_api:mmb_api"
      - "mmb_frontend:mmb_frontend"

  mmb_frontend:
    build:
      context: frontend
    depends_on:
      - mmb_api
    links:
      - "mmb_api:mmb_api"
    environment:
      - API_SERVER_ADDR=mmb_api:5500  
    ports:
      - 3000:3000 # host:container


  mmb_api:
    build:
      context: api
    stop_signal: SIGINT
    environment:
      - API_SERVER_ADDR=5500
      - FRONTEND_SERVER_ADDR=3000
      - DATABASE_CONNECTION_STRING=mongodb://mmb_mongo:27017
    volumes:
      - ./api:/src
    depends_on:
      -  mmb_mongo  
    links:
      - "mmb_mongo:mmb_mongo"

  mmb_mongo:
    image: mongo
    ports:
      - 27018:27017 # host:container
#    volumes:
#      - './mongo/db:/data/db'
