services:

  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
      - ./nginx/html:/etc/nginx/html
    environment: 
      - API_SERVER_ADDR=api:5000  
      - FRONTEND_SERVER_ADDR=frontend:3002  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 8080:80
    depends_on:
      - api
      - frontend
    links:
      - "api:api"
      - "frontend:frontend"

  frontend:
    build:
      context: frontend
      target: builder
    environment:
      - FRONTEND_SERVER_ADDR=3002

  api:
    build:
      context: api
      target: builder
    stop_signal: SIGINT
    environment:
      - API_SERVER_ADDR=5000
      - FRONTEND_SERVER_ADDR=3002
      - DATABASE_CONNECTION_STRING=mongodb://mongo:27017
    volumes:
      - ./api:/src
    depends_on:
      -  mongo  
    links:
      - "mongo:mongo"

  mongo:
    image: mongo
    ports:
      - 27018:27017 # host:container
    volumes:
      - './mongo/db:/data/db'
