services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - API_SERVER_ADDR=api:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 8080:80
    depends_on:
      - api

  api:
    build:
      context: api
      target: builder
    stop_signal: SIGINT
    environment:
      - API_SERVER_ADDR=9091
    volumes:
      - ./api:/src
    depends_on:
      -  mongo  
    links:
      - "mongo:mongo"

  mongo:
    image: mongo
    ports:
      - 27017:27017 # host:container
    volumes:
      - './mongo/db:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mmb
      MONGO_INITDB_ROOT_PASSWORD: mmb